/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg4saisons;

/**
 *
 * @author ybohouss
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        SpringButton.setEnabled(false);
        summerButton.setEnabled(false);          
        autumnButton.setEnabled(true);
        winterButton.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        winterButton = new javax.swing.JButton();
        autumnButton = new javax.swing.JButton();
        summerButton = new javax.swing.JButton();
        SpringButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        winterButton.setText("jButton1");
        winterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                winterButtonActionPerformed(evt);
            }
        });

        autumnButton.setText("jButton2");
        autumnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autumnButtonActionPerformed(evt);
            }
        });

        summerButton.setText("jButton3");
        summerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summerButtonActionPerformed(evt);
            }
        });

        SpringButton.setText("jButton4");
        SpringButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpringButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(summerButton)
                    .addComponent(winterButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(autumnButton)
                    .addComponent(SpringButton))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(winterButton)
                    .addComponent(autumnButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(summerButton)
                    .addComponent(SpringButton))
                .addGap(98, 98, 98))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void winterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_winterButtonActionPerformed
        // TODO add your handling code here:       
        clickWinter = true;
        if (clickAutumn)
            manageButtons(1);
        
    }//GEN-LAST:event_winterButtonActionPerformed

    private void autumnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autumnButtonActionPerformed
        // TODO add your handling code here:
        clickAutumn = true;
        if (clickWinter)
            manageButtons(1);
        
    }//GEN-LAST:event_autumnButtonActionPerformed

    private void SpringButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpringButtonActionPerformed
        // TODO add your handling code here:
        clickSpring = true;
        if (clickSummer)
            manageButtons(2);
    }//GEN-LAST:event_SpringButtonActionPerformed

    private void summerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summerButtonActionPerformed
        // TODO add your handling code here:
        clickSummer= true;
        if (clickSpring)
            manageButtons(2);
    }//GEN-LAST:event_summerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
            /*SpringButton.setEnabled(false);
            summerButton.setEnabled(false);          
            autumnButton.setEnabled(true);
            winterButton.setEnabled(true);*/

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    private void manageButtons(int job)
    {
        //job=1 => desac winter & autumn + acti summer & spring
        //job=2 => acti winter & autumn + desac summer & spring
        if(job == 1)
        {
            clickWinter = false;
            clickAutumn = false;
            
            SpringButton.setEnabled(true);
            summerButton.setEnabled(true);
            
            autumnButton.setEnabled(false);
            winterButton.setEnabled(false);
        }
        else
        {
            clickSpring = false;
            clickSummer = false;
            
            SpringButton.setEnabled(false);
            summerButton.setEnabled(false);
           
            autumnButton.setEnabled(true);
            winterButton.setEnabled(true);
            
            
        }
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SpringButton;
    private javax.swing.JButton autumnButton;
    private javax.swing.JButton summerButton;
    private javax.swing.JButton winterButton;
    // End of variables declaration//GEN-END:variables

    private Boolean clickSpring = false;
    private Boolean clickSummer = false;
    private Boolean clickWinter = false;
    private Boolean clickAutumn = false;
    
}
